DevChatter/devchatterbot

src/DevChatter.Bot.Core/Extensions/StringExtensions.cs
=> Nicer NoAT?

src/DevChatter.Bot.Core/Commands/FollowerCommand.cs, src/DevChatter.Bot.Core/Commands/SimpleCommand.cs, src/DevChatter.Bot.Core/Events/CommandReceivedEventArgs.cs, src/DevChatter.Bot.Core/Extensions/StringExtensions.cs, src/DevChatter.Bot.Core/Messaging/Tokens/SimpleToken.cs, src/DevChatter.Bot/FakeData.cs, src/UnitTests/Core/Commands/SimpleCommandTests/ProcessShould.cs, src/UnitTests/Core/Extensions/FindTokensShould.cs, src/UnitTests/Core/Messaging/SimpleTokenTests/ReplaceCommandValuesShould.cs
=> Adding Replacement Tokens

src/DevChatter.Bot.Core/Commands/AddQuoteCommand.cs, src/DevChatter.Bot.Core/Model/QuoteEntity.cs
https://github.com/DevChatter/devchatterbot/issues/31
=> Allowing Quote Adding

src/DevChatter.Bot.Core/Commands/RpsCommand.cs, src/DevChatter.Bot.Core/Commands/ShoutOutCommand.cs, src/DevChatter.Bot.Core/Games/RockPaperScissors/RockPaperScissors.cs, src/DevChatter.Bot.Core/Games/RockPaperScissors/RpsCommand.cs, src/DevChatter.Bot/FakeData.cs, src/DevChatter.Bot/Startup/SetUpBot.cs
=> Adding Rock Paper Scissors Game

src/DevChatter.Bot.Core/Commands/AddQuoteCommand.cs, src/DevChatter.Bot.Core/Commands/CoinsCommand.cs, src/DevChatter.Bot.Core/Commands/CommandsCommand.cs, src/DevChatter.Bot.Core/Commands/IBotCommand.cs, src/DevChatter.Bot.Core/Commands/QuoteCommand.cs, src/DevChatter.Bot.Core/Commands/ShoutOutCommand.cs, src/DevChatter.Bot.Core/Commands/SimpleCommand.cs, src/DevChatter.Bot.Core/Commands/StreamsCommand.cs, src/DevChatter.Bot.Core/Data/Model/ChatUser.cs, src/DevChatter.Bot.Core/Data/Model/StreamerEntity.cs, src/DevChatter.Bot.Infra.Ef/AppDataContext.cs, src/DevChatter.Bot.Infra.Ef/Migrations/20180327190522_StreamerData.Designer.cs, src/DevChatter.Bot.Infra.Ef/Migrations/20180327190522_StreamerData.cs, src/DevChatter.Bot/Startup/SetUpBot.cs, src/UnitTests/ScratchTesting.cs
This will resolve issue #45 by adding in a streams command.
=> Adding a Streams Command

src/DevChatter.Bot.Core/Events/CommandHandler.cs
!HanGMan and !Hangman will now both work.
(https://user-images.githubusercontent.com/37850395/38173315-9e406ee0-35bc-11e8-8f92-b7837616c4d1.JPG)
=> Make commands be case-insensitive.

src/DevChatter.Bot.Core/Games/Hangman/HangmanCommand.cs, src/DevChatter.Bot.Core/Games/Hangman/HangmanGame.cs, src/UnitTests/Core/Games/Hangman/HangmanGameTests/CalculateLetterAwardsShould.cs
Added losing hangman completing  #63 
Added points for letter guessers in hangman for #61 
Automatically win the game by guessing last hangman letter completing #62
=> Adding Hangman Features

src/DevChatter.Bot.Core/ChatUserCollection.cs, src/DevChatter.Bot.Core/Commands/GiveCommand.cs, src/DevChatter.Bot.Core/Events/CurrencyGenerator.cs, src/DevChatter.Bot/Startup/SetUpBot.cs, src/UnitTests/Core/Automation/CurrencyUpdateTests/IsTimeToRunShould.cs
=> Adding a give command for users to pass coins

src/DevChatter.Bot.Core/Commands/AddCommandCommand.cs, src/DevChatter.Bot.Core/Commands/RemoveCommandCommand.cs, src/DevChatter.Bot/Startup/SetUpBot.cs
Resolves #47 
Uses the AllCommands collection to add and remove the appropriate commands
=> Update Commands Live

src/DevChatter.Bot.Core/Commands/BonusCommand.cs, src/DevChatter.Bot.Core/Commands/GiveCommand.cs, src/DevChatter.Bot.Core/Commands/HelpCommand.cs, src/DevChatter.Bot.Core/Commands/IBotCommand.cs, src/DevChatter.Bot.Core/Commands/SimpleCommand.cs, src/DevChatter.Bot.Core/Events/CommandHandler.cs, src/DevChatter.Bot.Core/Extensions/StringExtensions.cs, src/UnitTests/Core/Events/CommandHandlerTests/CommandReceivedHandlerShould.cs, src/UnitTests/Fakes/FakeCommand.cs, src/UnitTests/UnitTests.csproj
=> Adding an IsEnabled property to commands

src/DevChatter.Bot.Core/Games/Hangman/HangmanGame.cs
Added the word after losing the game #83 
I hope the commits are not bad
=> Hangman show word after losing

src/DevChatter.Bot.Core/Commands/IBotCommand.cs, src/DevChatter.Bot.Core/Commands/UptimeCommand.cs, src/DevChatter.Bot.Core/Systems/Streaming/IStreamingInfoService.cs, src/DevChatter.Bot.Core/Systems/Streaming/StreamingPlatform.cs, src/DevChatter.Bot.Infra.Twitch/TwitchStreamingInfoService.cs, src/DevChatter.Bot/Startup/SetUpBot.cs
Adding a Uptime command for Twitch this resolves #78
=> Adding Uptime Command

src/DevChatter.Bot.Core/Commands/AddCommandCommand.cs, src/DevChatter.Bot.Core/Commands/AddQuoteCommand.cs, src/DevChatter.Bot.Core/Commands/BaseCommand.cs, src/DevChatter.Bot.Core/Commands/BonusCommand.cs, src/DevChatter.Bot.Core/Commands/CoinsCommand.cs, src/DevChatter.Bot.Core/Commands/CommandsCommand.cs, src/DevChatter.Bot.Core/Commands/GiveCommand.cs, src/DevChatter.Bot.Core/Commands/HelpCommand.cs, src/DevChatter.Bot.Core/Commands/IBotCommand.cs, src/DevChatter.Bot.Core/Commands/QuoteCommand.cs, src/DevChatter.Bot.Core/Commands/RemoveCommandCommand.cs, src/DevChatter.Bot.Core/Commands/ShoutOutCommand.cs, src/DevChatter.Bot.Core/Commands/SimpleCommand.cs, src/DevChatter.Bot.Core/Commands/StreamsCommand.cs, src/DevChatter.Bot.Core/Commands/UptimeCommand.cs, src/DevChatter.Bot.Core/Events/CommandHandler.cs, src/DevChatter.Bot.Core/Games/Hangman/HangmanCommand.cs, src/DevChatter.Bot.Core/Games/RockPaperScissors/RockPaperScissorsCommand.cs, src/UnitTests/Fakes/FakeCommand.cs
=> Improve Commands - Base and Aliases

src/DevChatter.Bot.Core/Commands/TopCommand.cs, src/UnitTests/Core/Commands/TopCommandTests/GenerateMessageShould.cs, src/UnitTests/Core/Commands/TopCommandTests/ProcessShould.cs
Tweaked the `TopCommand` with a new way of generating its message and added some tests around the message generation. Also made that method static.
=> Changes to TopCommand

src/DevChatter.Bot.Core/ChatUserCollection.cs, src/DevChatter.Bot.Core/Commands/BonusCommand.cs, src/DevChatter.Bot.Core/Data/Specifications/ChatUserPolicy.cs, src/DevChatter.Bot.Core/Events/CurrencyGenerator.cs, src/DevChatter.Bot.Core/IChatUserCollection.cs, src/UnitTests/Core/Automation/CurrencyUpdateTests/IsTimeToRunShould.cs
trying to fix some strange issues we noticed with the bonus command
=> Adjust Handling of ChatUser Updates

Dockerfile, docker-compose.yml
I love seeing CI on repositories, would you be interested in shipping this off to codeship or something to help with drive-by PRs?
=> Prove unit tests can work in Docker

README.md
The sentence was unclear, so I made an attempt to clarify it.
=> Clarify sentence in README

src/DevChatter.Bot.Core/Games/Mud/CharacterInfo.cs, src/DevChatter.Bot.Core/Games/Mud/FSM/MenuStates/ControlOptionState.cs, src/DevChatter.Bot.Core/Games/Mud/FSM/MenuStates/Menu.cs, src/DevChatter.Bot.Core/Games/Mud/FSM/MenuStates/OptionMenuState.cs, src/DevChatter.Bot.Core/Games/Mud/FSM/MenuStates/PlayGameState.cs, src/DevChatter.Bot.Core/Games/Mud/FSM/MenuStates/SoundOptionState.cs, src/DevChatter.Bot.Core/Games/Mud/FSM/PlayStates/GameStartState.cs, src/DevChatter.Bot.Core/Games/Mud/FSM/PlayStates/Level1.cs, src/DevChatter.Bot.Core/Games/Mud/FSM/PlayStates/Level2.cs, src/DevChatter.Bot.Core/Games/Mud/FSM/PlayStates/RoomState.cs, src/DevChatter.Bot.Core/Games/Mud/FSM/State.cs, src/DevChatter.Bot.Core/Games/Mud/FSM/StateMachine.cs, src/UnitTests/Core/Games/Mud/MudGameTests/MudFSMLevelLoad.cs
Needs more work and connection to chat systems.
=> Basic implementation of FSM

src/DevChatter.Bot.Core/Commands/BaseCommand.cs, src/DevChatter.Bot.Core/Commands/RouletteCommand.cs, src/DevChatter.Bot.Core/Data/ISettingsFactory.cs, src/DevChatter.Bot.Core/Data/Model/CommandSettingsEntity.cs, src/DevChatter.Bot.Core/Data/SettingsFactory.cs, src/DevChatter.Bot.Core/Data/Specifications/CommandSettingsPolicy.cs, src/DevChatter.Bot.Core/DevChatterBotCoreModule.cs, src/DevChatter.Bot.Core/Games/Roulette/RouletteCommand.cs, src/DevChatter.Bot.Core/Games/Roulette/RouletteSettings.cs, src/DevChatter.Bot.Core/Systems/Chat/IChatClient.cs, src/DevChatter.Bot.Infra.Ef/AppDataContext.cs, src/DevChatter.Bot.Infra.Ef/Migrations/20180609054837_Add-CommandSettings.Designer.cs, src/DevChatter.Bot.Infra.Ef/Migrations/20180609054837_Add-CommandSettings.cs, src/DevChatter.Bot.Infra.Ef/Migrations/20180609190031_RenameColumnToSettingsTypeName.Designer.cs, src/DevChatter.Bot.Infra.Ef/Migrations/20180609190031_RenameColumnToSettingsTypeName.cs, src/DevChatter.Bot.Infra.Twitch/TwitchChatClient.cs, src/DevChatter.Bot/Startup/SetUpDatabase.cs, src/UnitTests/Core/Data/SettingsFactoryTests/GetSettingsShould.cs
* By default there is a 20% chance to survive (Can be set in the database)
* Users get timed out(10 seconds by default) when the revolver shoots
(Duration can be set in the database)
* Subscribers can be protected which does not time them out (Can be
enabled/disabled in the database)
* Surviving rewards the user with coins(100 by default)
=> Add russian roulette command

src/DevChatter.Bot.Infra.Twitch/Events/TwitchFollowerService.cs, src/DevChatter.Bot.Infra.Twitch/TwitchClientSettings.cs, src/DevChatter.Bot.Infra.Twitch/TwitchStreamingInfoService.cs, src/DevChatter.Bot/appsettings.json
- Fix naming of ID to be Id #178
=> Fix naming of ID to be Id

src/DevChatter.Bot.Core/Games/Hangman/HangmanGame.cs, src/DevChatter.Bot/Startup/SetUpDatabase.cs, src/UnitTests/Core/Games/Hangman/HangmanGameTests/CalculateLetterAwardsShould.cs
Made hangman guesses by single letter case-insensitive. If a streamer adds words to the hangmanwords table in the database, containing capital letters, those letters can now be guessed.
=> Hangman bug resolved. Fixes #200

src/DevChatter.Bot.Core/Commands/ScheduleCommand.cs, src/DevChatter.Bot.Core/DevChatter.Bot.Core.csproj, src/DevChatter.Bot.Core/GoogleApi/PlaceResponse.cs, src/DevChatter.Bot.Core/GoogleApi/TimezoneResponse.cs, src/DevChatter.Bot.Core/GoogleCloudSettings.cs, src/DevChatter.Bot.Web/BotConfiguration.cs, src/DevChatter.Bot.Web/Startup.cs, src/DevChatter.Bot.Web/appsettings.json, src/UnitTests/Core/Commands/ScheduleCommandTests/ProcessShould.cs
Co-Authored-By: Simon Timms <stimms@users.noreply.github.com>
=> Adding Google API Lookup for Time by place

src/DevChatter.Bot.Core/Commands/ViewersCommand.cs, src/DevChatter.Bot.Core/Systems/Streaming/IStreamingInfoService.cs, src/DevChatter.Bot.Core/Systems/Streaming/IStreamingPlatform.cs, src/DevChatter.Bot.Core/Systems/Streaming/StreamingPlatform.cs, src/DevChatter.Bot.Infra.Twitch/TwitchStreamingInfoService.cs, src/DevChatter.Bot.Web/Extensions/ServiceCollectionExtensions.cs
Resolves #207 with this change.
=> Adding a Viewers Command

src/DevChatter.Bot.Core/Commands/SimpleCommand.cs, src/DevChatter.Bot.Core/Events/CommandHandler.cs, src/DevChatter.Bot.Core/IOverlayDisplay.cs, src/DevChatter.Bot.Infra.Web/Hubs/BotHub.cs, src/DevChatter.Bot.Infra.Web/HypeCommand.cs, src/DevChatter.Bot.Web/Pages/Overlay.cshtml, src/DevChatter.Bot.Web/wwwroot/js/overlay.js, src/DevChatter.Bot.Web/wwwroot/js/sprite.js
Causes the `!hype` command to blast devchaHype emotes from the center of the screen.
=> Canvas Hype

src/DevChatter.Bot.Web/wwwroot/js/sprite.js
Small change to the sprite.js which sends hype in every direction. Hope I can make more meaningful contributions to the project in the future.
=> Random directional sprites

src/DevChatter.Bot.Core/Commands/Operations/AddAliasOperation.cs, src/DevChatter.Bot.Core/Commands/RefreshCommandListCommand.cs, src/DevChatter.Bot.Core/Commands/Trackers/CommandList.cs, src/DevChatter.Bot.Core/DevChatter.Bot.Core.csproj, src/DevChatter.Bot.Core/Events/CommandHandler.cs, src/DevChatter.Bot.Web/Extensions/ServiceCollectionExtensions.cs, src/UnitTests/Core/Events/CommandHandlerTests/CommandReceivedHandlerShould.cs
Some refactoring, fixing naming, etc. during the SRP stream for our first SOLID Saturday.
=> Refresh Command and Code Clean-Up

src/DevChatter.Bot.Core/Games/Hangman/HangmanGame.cs
I wasn't able to build it locally, but I think this will work for you.
=> Add letter validation to hangman

src/DevChatter.Bot.Core/Games/Hangman/HangmanGame.cs, src/DevChatter.Bot.Core/Games/Hangman/HangmanSettings.cs, src/DevChatter.Bot.Web/appsettings.json
Closes https://github.com/DevChatter/devchatterbot/issues/265
Checks to make sure guesses are English letters. Tested with emojis, symbols and numbers.
=> Hangman: Only English Characters
